namespace surgical_reports.entities;

public class Class_CABG
    {
        public int Id { get; set; }
        public int PROCEDURE_ID { get; set; }
        public int PATIENT_ID { get; set; }
        public string CAB { get; set; }
        public string UNPLANNED_CAB { get; set; }
        public string B1_SITE { get; set; }
        public string B1_TYPE_DA { get; set; }
        public string B1_LOCPROC { get; set; }
        public string B1_CONDUIT { get; set; }
        public string B1_SITEPA { get; set; }
        public string B1_DONOR { get; set; }
        public string B2_SITE { get; set; }
        public string B2_TYPE_DA { get; set; }
        public string B2_LOCPROC { get; set; }
        public string B2_CONDUIT { get; set; }
        public string B2_SITEPA { get; set; }
        public string B2_DONOR { get; set; }
        public string B3_SITE { get; set; }
        public string B3_TYPE_DA { get; set; }
        public string B3_LOCPROC { get; set; }
        public string B3_CONDUIT { get; set; }
        public string B3_SITEPA { get; set; }
        public string B3_DONOR { get; set; }
        public string B4_SITE { get; set; }
        public string B4_TYPE_DA { get; set; }
        public string B4_LOCPROC { get; set; }
        public string B4_CONDUIT { get; set; }
        public string B4_SITEPA { get; set; }
        public string B4_DONOR { get; set; }
        public string B5_SITE { get; set; }
        public string B5_TYPE_DA { get; set; }
        public string B5_LOCPROC { get; set; }
        public string B5_CONDUIT { get; set; }
        public string B5_SITEPA { get; set; }
        public string B5_DONOR { get; set; }
        public string B6_SITE { get; set; }
        public string B6_TYPE_DA { get; set; }
        public string B6_LOCPROC { get; set; }
        public string B6_CONDUIT { get; set; }
        public string B6_SITEPA { get; set; }
        public string B6_DONOR { get; set; }
        public string Q01 { get; set; }
        public string Q02 { get; set; }
        public string Q03 { get; set; }
        public string Q04 { get; set; }
        public string Q05 { get; set; }
        public string Q06 { get; set; }
        public string ANGLE01 { get; set; }
        public string ANGLE02 { get; set; }
        public string ANGLE03 { get; set; }
        public string ANGLE04 { get; set; }
        public string ANGLE05 { get; set; }
        public string ANGLE06 { get; set; }
        public string DIAM01 { get; set; }
        public string DIAM02 { get; set; }
        public string DIAM03 { get; set; }
        public string DIAM04 { get; set; }
        public string DIAM05 { get; set; }
        public string DIAM06 { get; set; }
        public string course { get; set; }
        public string leg_harvest_location { get; set; }
        public string radial_harvest_location { get; set; }
        public string leg_harvest_technique { get; set; }
        public string radial_harvest_technique { get; set; }
        public string art01 { get; set; }
        public string art02 { get; set; }
        public string art03 { get; set; }
        public string art04 { get; set; }
        public string art05 { get; set; }
        public string art06 { get; set; }
        public int tachtig_switch { get; set; }
    }
